name: tests

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-22.04 # 明确运行环境

    steps:
      # 1. 检出代码仓库
      - name: Checkout the repository
        uses: actions/checkout@v3

      # 2. 设置 JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17       # 请确保与 pom.xml 中的版本一致
          distribution: 'temurin' # 推荐使用 Temurin JDK

      # 3. 缓存 Maven 依赖
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      # 4. 运行 Maven 测试
      - name: Run tests with Maven
        run: mvn -B clean test --file pom.xml # 具体到自己的 pom.xml 文件位置
