# .github/workflows/yzr.yml
name: Maven Tests

# 触发条件：当代码推送到主分支或发起 Pull Request 时触发
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# 定义任务
jobs:
  run_tests:
    # 运行环境，使用最新的 Ubuntu 系统
    runs-on: ubuntu-latest

    # 定义任务的具体步骤
    steps:
      # 1. 检出代码仓库
      - name: Checkout the repository
        uses: actions/checkout@v2

      # 2. 设置 Java 开发环境
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17 # 确保与 Maven 项目中的 JDK 版本一致
          distribution: 'adopt' # 使用 AdoptOpenJDK

      # 3. 缓存 Maven 依赖
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository # Maven 本地依赖的默认路径
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4. 使用 Maven 构建项目并运行测试
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml
